{{- if ((.Values.api).enabled) | default true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: clusterpulse
    component: api
rules:
# OpenShift user/group resolution
- apiGroups: ["user.openshift.io"]
  resources: ["users"]
  verbs: ["get"]
- apiGroups: ["user.openshift.io"]
  resources: ["groups"]
  verbs: ["get", "list"]
{{- end }}

