{{- if ((.Values.api).enabled) | default true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: clusterpulse
    component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-api
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
{{- end }}
