{{- if ((.Values.api).enabled) | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: clusterpulse
    component: api
{{- end }}

