# operator/helm-charts/clusterpulse/templates/ui/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
immutable: false
data:
  default.conf: |-
    upstream backend {
        server {{ .Release.Name }}-api.{{ .Release.Namespace }}.svc.cluster.local:8080;
    }

    server {
        listen {{ (((.Values.frontend).nginx).port) | default 8080 }};

        # API calls go to internal backend
        location /api/ {
            proxy_pass http://backend/api/;
            proxy_http_version 1.1;

            # Pass OAuth headers from OAuth proxy
            proxy_set_header X-Forwarded-User $http_x_forwarded_user;
            proxy_set_header X-Forwarded-Email $http_x_forwarded_email;

            # Standard proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Timeouts
            proxy_connect_timeout {{ ((((.Values.frontend).nginx).upstreamTimeout).connect) | default "60s" }};
            proxy_send_timeout {{ ((((.Values.frontend).nginx).upstreamTimeout).send) | default "60s" }};
            proxy_read_timeout {{ ((((.Values.frontend).nginx).upstreamTimeout).read) | default "60s" }};
        }

        {{- if (((.Values.frontend).nginx).websocket) | default true }}
        # WebSocket support for live updates
        location /api/ws {
            proxy_pass http://backend/api/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        {{- end }}

        # Frontend files
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }
    }

