api:
  image: quay.io/clusterpulse/api:v1.0.0
frontend:
  image: quay.io/clusterpulse/ui:v1.0.0
policyEngine:
  image: quay.io/clusterpulse/policy-controller:v0.3.0
clusterEngine:
  image: quay.io/clusterpulse/cluster-controller:v1.0.0
redis:
  image:
    tag: latest
