api:
  image: quay.io/clusterpulse/api:v1.0.0
frontend:
  image: quay.io/clusterpulse/ui:v1.0.0
clusterEngine:
  image: quay.io/clusterpulse/cluster-controller:v1.0.0
  ingester:
    enabled: false
redis:
  image:
    tag: latest
defaults:
  metricsources:
    enabled: true
