apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-policy-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-policy-controller
  namespace: {{ .Release.Namespace }}
