apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policy-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: clusterpulse
    component: policy-controller
spec:
  selector:
    component: policy-controller
  ports:
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
