apiVersion: clusterpulse.io/v1alpha1
kind: MonitorAccessPolicy
metadata:
  name: example
spec:
  access:
    effect: Allow
    enabled: true
  identity:
    priority: 100
    subjects:
      groups:
        - default-group
      users:
        - default-user
  scope:
    clusters:
      default: none
      rules:
        - permissions:
            view: true
            viewMetrics: true
          resources:
            - type: nodes
              visibility: all
            - type: operators
              visibility: all
            - type: namespaces
              visibility: all
            - type: pods
              visibility: all
            - type: deployment-metrics
              visibility: all
          selector:
            matchPattern: .*
