apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: registryconnections.clusterpulse.io
spec:
  group: clusterpulse.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - endpoint
            properties:
              displayName:
                type: string
                description: Human-friendly name for the registry
              endpoint:
                type: string
                description: Registry endpoint URL
              type:
                type: string
                description: Optional type identifier for the registry (informational only)
              credentialsRef:
                type: object
                description: Reference to secret containing credentials
                properties:
                  name:
                    type: string
                    description: Name of the secret
                  namespace:
                    type: string
                    description: Namespace of the secret
                required:
                - name
              insecure:
                type: boolean
                description: Allow insecure HTTP connections
                default: false
              skipTLSVerify:
                type: boolean
                description: Skip TLS certificate verification
                default: false
              monitoring:
                type: object
                properties:
                  interval:
                    type: integer
                    description: Check interval in seconds
                    minimum: 30
                    default: 60
                  timeout:
                    type: integer
                    description: Request timeout in seconds
                    minimum: 5
                    default: 10
                  checkCatalog:
                    type: boolean
                    description: Enable catalog endpoint checking
                    default: false
                  maxCatalogEntries:
                    type: integer
                    description: Maximum catalog entries to fetch
                    minimum: 1
                    maximum: 1000
                    default: 100
              labels:
                type: object
                additionalProperties:
                  type: string
                description: Labels for registry categorization
              healthCheckPaths:
                type: array
                items:
                  type: string
                description: Additional paths to check for health
                default:
                - "/v2/"
          status:
            type: object
            properties:
              phase:
                type: string
                description: Current phase (Connecting, Connected, Error, Unknown)
              health:
                type: string
                description: Health status (healthy, degraded, unhealthy, unknown)
              available:
                type: boolean
                description: Whether registry is reachable
              lastCheckTime:
                type: string
                format: date-time
                description: Last health check timestamp
              responseTime:
                type: integer
                description: Response time in milliseconds
              message:
                type: string
                description: Status message
              repositoryCount:
                type: integer
                description: Number of repositories (if catalog enabled)
              version:
                type: string
                description: Registry version
              features:
                type: object
                additionalProperties:
                  type: boolean
                description: Detected registry features
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Display Name
      type: string
      jsonPath: .spec.displayName
    - name: Endpoint
      type: string
      jsonPath: .spec.endpoint
    - name: Type
      type: string
      jsonPath: .spec.type
    - name: Available
      type: boolean
      jsonPath: .status.available
    - name: Health
      type: string
      jsonPath: .status.health
    - name: Response Time
      type: integer
      jsonPath: .status.responseTime
      description: Response time in ms
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: registryconnections
    singular: registryconnection
    kind: RegistryConnection
    shortNames:
    - rc
    - regcon
