apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cluster-controller
rules:
- apiGroups:
  - clusterpulse.io
  resources:
  - clusterconnections
  - registryconnections
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Permissions to update ClusterConnection status
- apiGroups:
  - clusterpulse.io
  resources:
  - clusterconnections/status
  - registryconnections/status
  verbs:
  - get
  - update
  - patch

# Policy controller permissions (now integrated)
- apiGroups:
  - clusterpulse.io
  resources:
  - monitoraccesspolicies
  verbs:
  - get
  - list
  - watch
  - patch

- apiGroups:
  - clusterpulse.io
  resources:
  - monitoraccesspolicies/status
  verbs:
  - get
  - update
  - patch

# MetricSource Permissions
- apiGroups:
  - clusterpulse.io
  resources:
  - metricsources
  verbs:
  - get
  - list
  - watch
  - patch

- apiGroups:
  - clusterpulse.io
  resources:
  - metricsources/status
  verbs:
  - get
  - update
  - patch

# Permissions to read secrets (for cluster credentials)
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

# Permissions for events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# Permissions for operator state
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# OpenShift user/group resolution (for policy engine)
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - get

- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
